Regression: Handle invalid token error
Now that we are returning json for invalid token error the CLI
was throwing this error:

```
  File "/Users/naren/Code/floyd/floyd-cli/floyd/model/user.py", line 14,
  in make_user
      return User(**data)
    TypeError: __init__() missing 4 required positional arguments:
    'uid', 'username', 'email', and 'type'
```

This was because the login client was not using the same base web client
as the other clients.