fix(crash): close data.gar file descriptor after upload
A leaked file descriptor will cause the following error in Windows:

PermissionError: [WinError 32] The process cannot access the file
because it is being used by another process